import React, {Component} from 'react';
import './App.css';


class App extends Component {
  constructor(props){
    super(props);
      this.state = {
        todo: [],
        todoInputValue: ''
      }
  }

  handleTodoInputChange = (e) => {
    console.log(e.target.value);
    this.setState({todoInputValue: e.target.value})
  }

  handleAddTodoClick = (e) =>{
    e.preventDefault();
    //stops the form from 'jumping'

    var toDo = {
      id:Date.now(),
      content: this.state.todoInputValue,
    }

    //id is generated by server and contents
    // pulled by the todoInputValue

    var newTodo = [...this.state.todo, toDo]

    // new bucket that adds toDo bucket to existing list

    this.setState({
      todo: newTodo,
      todoInputValue: ''
    })
  }

  removeTodo = (todoId) => {
    var todo = this.state.todo;
    var filteredTodo = todo.filter(function(todoItem){
      return (todoItem.id !== todoId);
    });

    this.setState({todo:filteredTodo});
  }

  render () {
    return (      

      <div className="wrapper">
        <div className="banner">
                <div>
                    <i className="fas fa-bars"></i>
                    <i className="fas fa-cog"></i>
                </div>
            <h1>
                Today's List
            </h1>
        </div>

        <div className="todo">

          {this.state.todo.map((todoItem) => {
            return (
              <div className="item" key={todoItem.id}>
                  <i className="fas fa-minus-circle" onClick={(e) => { this.removeTodo(todoItem.id) }}></i>
                  <div>{todoItem.content}</div>
              </div>
            )
          })} 

            <form className="item" action="">
                <div>Add new item</div>
                <input type="text" className="todo-input" value={this.state.todoInputValue} onChange={this.handleTodoInputChange}/>
                <button onClick={this.handleAddTodoClick}>Add</button>
            </form>
        </div>
    </div>
    )
  }
}

export default App;
